export const fallbackCafes = [
  {
    id: 'blue-and-beyond',
    name: 'Blue & Beyond',
    area: 'New Town',
    address: 'The Westin, Plot No. 01, New Town',
    lat: 22.5797,
    lng: 88.4631,
    rating: 4.6,
    price: 2,
    priceLabel: '₹₹',
    wifi: true,
    power: true,
    tags: ['Work-friendly', 'Rooftop'],
    note: 'Quiet tables, quick Wi‑Fi and a view that makes deadlines easier.',
    hours: 'Open until 11:00 pm',
    accent: 'from-[#f0d2b7] to-[#b86f58]',
  },
  {
    id: 'roastery-coffee-house',
    name: 'Roastery Coffee House',
    area: 'Hindustan Park',
    address: '70B, Hindustan Park, Gariahat',
    lat: 22.5168,
    lng: 88.3627,
    rating: 4.7,
    price: 2,
    priceLabel: '₹₹',
    wifi: true,
    power: true,
    tags: ['Specialty coffee', 'Popular'],
    note: 'Slow mornings, single-origin pours and plenty of natural light.',
    hours: 'Open until 10:30 pm',
    accent: 'from-[#dbc2a4] to-[#83624f]',
  },
  {
    id: 'wise-owl',
    name: 'The Wise Owl Steakhouse',
    area: 'Park Street',
    address: '55A, Mirza Ghalib Street, Park Street',
    lat: 22.5532,
    lng: 88.3524,
    rating: 4.5,
    price: 3,
    priceLabel: '₹₹₹',
    wifi: true,
    power: false,
    tags: ['Late night', 'Comfort food'],
    note: 'A lively all-day spot when you need coffee with your company.',
    hours: 'Open until 12:00 am',
    accent: 'from-[#d4b4a0] to-[#765548]',
  },
  {
    id: 'calcutta-64',
    name: 'Calcutta 64',
    area: 'Salt Lake',
    address: '64, Sector 1, Salt Lake City',
    lat: 22.5906,
    lng: 88.4082,
    rating: 4.4,
    price: 2,
    priceLabel: '₹₹',
    wifi: true,
    power: true,
    tags: ['Work-friendly', 'Brunch'],
    note: 'Spacious corners, hearty brunches and tables made for long stays.',
    hours: 'Open until 10:00 pm',
    accent: 'from-[#b8c6aa] to-[#60725c]',
  },
  {
    id: '8th-day-cafe',
    name: '8th Day Café & Bakery',
    area: 'Ballygunge',
    address: '6, Allenby Road, Ballygunge',
    lat: 22.5317,
    lng: 88.3632,
    rating: 4.6,
    price: 2,
    priceLabel: '₹₹',
    wifi: true,
    power: true,
    tags: ['Bakery', 'Calm'],
    note: 'Fresh bakes and a calm playlist for a gentle afternoon reset.',
    hours: 'Open until 9:30 pm',
    accent: 'from-[#e2ccb6] to-[#b78269]',
  },
  {
    id: 'cafe-culture',
    name: 'Cafe Culture',
    area: 'Camac Street',
    address: '8, Elgin Road, near Camac Street',
    lat: 22.5461,
    lng: 88.3528,
    rating: 4.2,
    price: 1,
    priceLabel: '₹',
    wifi: false,
    power: false,
    tags: ['Budget-friendly', 'Quick bite'],
    note: 'No-fuss filter coffee and snacks when you are on a budget.',
    hours: 'Open until 9:00 pm',
    accent: 'from-[#e0c9a0] to-[#ae7847]',
  },
]
